### ISSUE TITLE
what was the first website you made?

### ISSUE THREAD

**Issue by dydx** [mdo/ama#154]
Not specifically the first professional one that you got paid for, but the first one you put online for the world to see.

**Comment by mdo** [comment]
I had a few sites early on that hosted my wallpapers, icons, and Windows XP themes from Deviant Art. It was made with Notepad and hosted on Geocities. It was super dark, rather janky, and really not good looking lol. The earliest ones used a lot of `<frame>`s too haha. The first paid one was for a local lawyer (plaintiff broker actually), but he's since had a new site put up.
