### ISSUE TITLE
What are some projects to contribute to for someone new to open source?

### ISSUE THREAD

**Issue by danielcgold** [mdo/ama#156]
...specifically for html/css/js stuff. What are some of your favorite projects that are fun to work on? What would you suggest someone new to open sourcing start contributing to?

**Comment by mdo** [comment]
I'd [search by language](https://github.com/search?o=desc&q=language%3Ahtml+language%3Acss&ref=searchresults&s=stars&type=Repositories&utf8=✓) and see if anything appeals to you.

Also, try finding bigger projects you recognize and see if they need anything around bug fixes, spell checking, readmes (either entire readmes or updates), linting changes, etc. My favorite ones to work on are the ones I've put out there, but only because I don't have time with all those to contribute to much else haha.
