### ISSUE TITLE
Ads 

### ISSUE THREAD

**Issue by rambleraptor** [mdo/ama#159]
I noticed that you run ads on Code Guide and your personal site. Do you make enough money off of those ads for it to be worthwhile? What are your thoughts about running ads on open source websites?

**Comment by mdo** [comment]
It's not much on those sites, but it's nice to see a kickback every now and then for the few hours I've put into the projects. It's also a gentle reminder that folks continue to use these pages and that they're of value to others, so it keeps me motivated to their presence :).

Running ads on OS sites makes sense to me honestly, so long as they're not egregious or intrusive. I like stuff like Carbon and The Deck since that form factor is compact and lightweight. Folks should be able to earn _something_ monetarily for their efforts. I think it's foolhardy to expect a lot from those ads, but at the same time it's a small and subtle way to show project maintainers some support for their work.
