### ISSUE TITLE
jekyll includes and font-awesome

### ISSUE THREAD

**Issue by zbeekman** [mdo/ama#175]
I have a question regarding [this blog post](http://markdotto.com/2014/02/28/including-css-in-jekyll/):

How do you include the font-awesome css and have access to the contents of the fonts folder? I'm new to jekyll and web programming/design, but it seems that, for my project, the `font-awesome.css` file gets included into `style.css` which is put under `_site/style.css` and within the `font-awesome.css` there are references to assets in the `font-awesome/fonts/` directory. Also, `font-awesome.css` has to live in a subdirectory or `_include` for it to be included via `{% include ... %}` but other assets of that folder don't get copied to `_site` If I include this directory at the project root, then it will get copied over and everything works OK, but this seems like a hack and odd home for this.

**Comment by mdo** [comment]
The http://markdotto.com/2014/09/25/sass-and-jekyll/ post might be more helpful since it uses some easy built in functionality for Jekyll around CSS imports (Sass or not). I suppose the `include` method would be fine for that so long as you have the empty frontmatter (those `---` up top).

You might want to read through the Jekyll docs for a better understanding of how things are included. It's a bit tough for me to explain here in any meaningful way compared to that.
