### ISSUE TITLE
View list of followers/following/starred repos on mobile GitHub?

### ISSUE THREAD

**Issue by mikemcbride** [mdo/ama#182]
I realize that the mobile version of the app aims to target the most-used features, but I'm curious if there are plans to add the ability to view followers/following/starred repos from a user's profile page? Seems like it might be a quick win since you display lists of repos and users elsewhere (I don't mean to trivialize this)?

![mobile_gh_profile_links](https://cloud.githubusercontent.com/assets/6248612/9762783/555e6934-56cb-11e5-9f2a-cb5b3a13c81d.png)

**Comment by mdo** [comment]
Since we don't have mobile optimized views for those, we didn't link them up. There's likely little benefit to us building those views up right now in comparison to other things. That's super shitty to say and hear I know, so apologies. We might get to it in time, but I've no idea when that'll be <3.

**Comment by mikemcbride** [comment]
No worries. Appreciate the response :smile:
