### ISSUE TITLE
Moving off of Slack

### ISSUE THREAD

**Issue by vjeux** [mdo/ama#194]
Hey, I've seen your tweet about Bootstrap reaching Slack's limits. I was involved in finding a replacement for Reactiflux and found out/promoted Discord.

Let me know if you have any questions about it, would love to chat. It's been a very difficult process but I think we landed on something good.

My email: vjeux@fb.com

**Comment by mdo** [comment]
Hey there!

Thanks for reaching out! So far I've only played with it a little bit with a few random folks. I plan on sending the Discord folks an email as well—they've already reached out on Twitter, too, so that's rad. Slack's done nothing like that so it already feels better :laughing:.

The few things I've run into include:
- Since this is code related, I expect snippets of code to be shared. Right now that stuff isn't really handled well at all.
- Performance seems a little rough at times—particularly the speed at which keystrokes actually register while typing comments.
- Hubot integration is something I'd love to have and am looking into that. I see there's already an adapter (found on here on GitHub), but will need to fiddle with it to set it up.
- I think I've disabled it (for `@everyone`), but voice chat isn't something we need or want at all. 

Still haven't dug in too much, but so far I dig a lot of it.

**Comment by vjeux** [comment]
For snippets they just added the ability to do codeblocks by doing

``````
```javascript
some.code();
```
``````

Hmm i've never experienced that keystroke lagginess. Definitely worth checking what's going on with them.

For the integrations they have an api. Will probably require a bit of fiddling with it but shouldn't be too hard.

For voice chat, you can disable it. But even if enabled, it's a separate channel so anyone that wants to talk with voice can go there without annoying anyone.

Yeah the fact that it's possible to talk to someone on their team is really valuable. We tried to reach out to Slack via many ways, including friends of friends and only got ignored :(

**Comment by mdo** [comment]
Closing out—still on Slack for now, but will keep an eye out on things if we need to switch. Thanks again!
