### ISSUE TITLE
Versioning in open source projects?

### ISSUE THREAD

**Issue by marcelosomers** [mdo/ama#199]
Hey Mark,
Thanks again for opening up this repo and making yourself so accessible! Definitely appreciate it.

I've just launched [my first open source project](http://github.com/patternpack/patternpack), and we've started getting issues/bugfixes from the community. How does Bootstrap handle bugfixes? Clearly you don't do a patch release for every bug, so what warrants a new release, and until that release comes out, are you comfortable with letting bugs sit?

Would love to hear your thoughts on this!

**Comment by mdo** [comment]
Yeah, we try to bundle things a bit. For example, maybe we'd prioritize docs improvements or a specific component's updates. Beyond that, we play it by ear.

Getting on a schedule would be best for you and your users though—that's something we never locked down with Bootstrap and more. Releases happen when I can coordinate with everyone, test the changes, write a blog post, etc.

We do all our development in `master` too, so folks who want to pick up a fix can either `cherry-pick` commits or pull down the latest code instead of a release. That way, the time between releases isn't so terrible for folks who really can't wait on a fix.
