### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by rethabile-dev** [mdo/ama#207]
For someone starting with Bootstrap like me,  would you suggest Bootstrap 4 or Bootstrap 3?

Suppose I start with Bootstrap 3, how hard would it be to move to Bootstrap 4 at a later stage? Also, for how long will Bootstrap 3 be supported now that there is Bootstrap 4 coming?

**Comment by mdo** [comment]
Bootstrap 3's not under active development, but we are doing critical bug fixes and docs improvements while focusing on v4. I'd suggest learning the ropes with v3 since it's been out for years now and there's been plenty written about it. I wouldn't dive into v4 too deeply until our first betas (still alpha right now).

**Comment by rethabile-dev** [comment]
Thanks!
