### ISSUE TITLE
Starting out.

### ISSUE THREAD

**Issue by Lagastic** [mdo/ama#224]
Hi, 
I understand that you started out in high school with freelancing and later dropped out of college to move to sf. Well, I was wondering, what did you do as a freelancer? Web design or something alike? And did you get paying customers from the start?

**Comment by mdo** [comment]
Yup, I did small web projects for local businesses. Nothing too major, but I did start it early in high school. I always had paying customers—I didn't like doing work for free, and no one should really have to either. Most projects were either simple static sites or Wordpress powered sites so that customers could easily add more pages, photos, etc.
